services:
  redis:
    container_name: redis_container
    image: redis:8-alpine
    restart: always
    ports:
      - '6379:6379'
    command: redis-server --loglevel warning
    volumes:
      - redis_data:/data
    networks:
      - url_shortener_network

  cassandra:
    container_name: cassandra_container
    image: cassandra:latest
    restart: always
    ports:
      - '9042:9042'
    volumes:
      - cassandra_data:/var/lib/cassandra
    networks:
      - url_shortener_network

  postgres:
    container_name: postgres_container
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=url_shortener
      - POSTGRES_DB=url_shortener_users
      - POSTGRES_PASSWORD=api
    ports:
      - '5432:5432'
    volumes:
      - postgres_data:/var/lib/postgresql
    networks:
      - url_shortener_network

  elasticsearch:
    container_name: elasticsearch_container
    image: elasticsearch:8.17.0
    restart: always
    ports:
      - '9200:9200'
    environment:
      ES_JAVA_OPTS: -Xmx1g -Xms1g
      bootstrap.memory_lock: 'true'
      discovery.type: single-node
      network.host: 0.0.0.0
      transport.host: 127.0.0.1
      http.host: 0.0.0.0
      xpack.security.enabled: 'true'
      xpack.security.authc.api_key.enabled: 'true'
      xpack.monitoring.collection.enabled: 'true'
      xpack.security.enrollment.enabled: 'true'
      xpack.security.authc.token.enabled: 'true'
      ELASTIC_PASSWORD: admin1234

  zookeeper:
    container_name: zookeeper_container
    image: zookeeper:latest
    restart: always
    ports:
      - '2181:2181'
    volumes:
      - zookeeper_data:/data
    networks:
      - url_shortener_network

  rabbitmq:
    container_name: rabbitmq_container
    image: rabbitmq:4.0-management-alpine
    restart: always
    environment:
      - RABBITMQ_DEFAULT_USER=url_shortener
      - RABBITMQ_DEFAULT_PASS=api
    ports:
      - '5672:5672'
      - '15672:15672'
    networks:
      - url_shortener_network


networks:
  url_shortener_network:
    driver: bridge

volumes:
  redis_data:
  cassandra_data:
  zookeeper_data:
  postgres_data: