apiVersion: v1
kind: PersistentVolume
metadata:
  name: cassandra-pv
spec:
  storageClassName: cassandra-local-storage
  capacity:
    storage: 4Gi
  accessModes:
    - ReadWriteOnce
  hostPath:
    path: /var/lib/cassandra
    type: DirectoryOrCreate
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: cassandra-pvc
  namespace: url-shortener
spec:
  storageClassName: cassandra-local-storage
  resources:
    requests:
      storage: 4Gi
  accessModes:
    - ReadWriteOnce
