apiVersion: apps/v1
kind: Deployment
metadata:
  name: url-notifications
  namespace: url-shortener
spec:
  replicas: 1
  selector:
    matchLabels:
      app: url-notifications
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxUnavailable: 25%
      maxSurge: 25%
  template:
    metadata:
      labels:
        app: url-notifications
    spec:
      containers:
        - name: url-notifications
          image: colakkemree/url-shortener-notifications:stable
          imagePullPolicy: Always
          resources:
            limits:
              cpu: '0.5'
              memory: 1Gi
            requests:
              cpu: 100m
              memory: 150Mi
          ports:
            - name: notifications
              containerPort: 4004
          env:
            - name: ENABLE_APM
              value: '1'
            - name: NODE_ENV
              value: 'production'
            - name: REDIS_HOST
              valueFrom:
                secretKeyRef:
                  name: url-backend-secret
                  key: url-redis-host
            - name: CLIENT_URL
              value: 'http://localhost:3000'
            - name: RABBITMQ_ENDPOINT
              valueFrom:
                secretKeyRef:
                  name: url-backend-secret
                  key: url-rabbitmq-endpoint
            - name: SENDER_EMAIL
              valueFrom:
                secretKeyRef:
                  name: url-backend-secret
                  key: sender-email
            - name: SENDER_EMAIL_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: url-backend-secret
                  key: sender-email-password
            - name: ELASTIC_SEARCH_URL
              valueFrom:
                secretKeyRef:
                  name: url-backend-secret
                  key: url-elasticsearch-url
            - name: ELASTIC_APM_SERVER_URL
              valueFrom:
                secretKeyRef:
                  name: url-backend-secret
                  key: url-elastic-apm-server-url
            - name: ELASTIC_APM_SECRET_TOKEN
              valueFrom:
                secretKeyRef:
                  name: url-backend-secret
                  key: url-elastic-apm-secret-token
