apiVersion: v1
kind: Service
metadata:
  name: url-notifications
  namespace: url-shortener
spec:
  type: ClusterIP
  selector:
    app: url-notifications
  ports:
    - name: notifications
      port: 4004
      targetPort: 4004
      protocol: TCP
