apiVersion: v1
kind: Service
metadata:
  name: url-redis
  namespace: url-shortener
spec:
  type: ClusterIP
  selector:
    app: url-redis
  ports:
    - name: url-redis
      port: 6379
      targetPort: 6379
