apiVersion: v1
kind: Service
metadata:
  name: url-postgres
  namespace: url-shortener
spec:
  type: ClusterIP
  selector:
    app: url-postgres
  ports:
    - name: url-postgres
      port: 5432
      targetPort: 5432
