apiVersion: v1
kind: Service
metadata:
  name: url-auth
  namespace: url-shortener
spec:
  type: ClusterIP
  selector:
    app: url-auth
  ports:
    - name: auth
      port: 4003
      targetPort: 4003
      protocol: TCP
