apiVersion: v1
kind: Service
metadata:
  name: url-generate
  namespace: url-shortener
spec:
  type: ClusterIP
  selector:
    app: url-generate
  ports:
    - name: url-generate
      port: 4002
      targetPort: 4002
      protocol: TCP
